Repository m3ntorship/m3ntorship-ui, pull requests merged in 2022-06, with the labels that each got.

#12 add Dockerfile and .dockerignore files
  Dockerfile
Labels: in progress

#22 Fix eslint configs
  .eslintrc.js
  .github/workflows/main.yml
  .vscode/settings.json
  package.json
  tsconfig.eslint.json
  yarn.lock
Labels: ready for review

#20 Tailwind config values
  tailwind.config.js
  tailwind.css
  utils/tailwind/figmaTokens.json
  utils/tailwind/tailwindHelpers.js
Labels: ready for review

#23 Component structure ex
  .husky/pre-commit
  .storybook/main.js
  package.json
  src/ExComponent/ExComponent.stories.tsx
  src/ExComponent/ExComponent.tsx
  src/ExComponent/types.ts
  stories/Button.stories.tsx
  stories/Thing.stories.tsx
  test/blah.test.tsx
  yarn.lock
Labels: ready for review

#25 Create Button component
  .storybook/main.js
  .vscode/settings.json
  declaration.d.ts
  package.json
  src/Button/Button.module.css
  src/Button/Button.stories.tsx
  src/Button/Button.tsx
  src/Button/types.ts
  tailwind.css
  tsconfig.json
  utils/tailwind/figmaTokens.json
  yarn.lock
Labels: ready for merge

#31 Add link component
  .github/workflows/main.yml
  .prettierrc
  jest.config.js
  package.json
  src/Link/Link.stories.tsx
  src/Link/Link.test.tsx
  src/Link/Link.tsx
  src/Link/Link.types.ts
  src/Link/__snapshots__/Link.test.tsx.snap
  src/Typography/Typography.module.css
  src/Typography/Typography.stories.tsx
  src/Typography/Typography.test.tsx
  src/Typography/Typography.tsx
  src/Typography/Typography.types.ts
  src/Typography/__snapshots__/Typography.test.tsx.snap
  tailwind.config.js
  tsconfig.json
Labels: ready for review, ready for merge

#28 Add typography component
  src/Typography/Typography.tsx
Labels: ready for review, ready for merge

#37 Svg storybook support
  .storybook/main.js
  package.json
  src/types/svg.d.ts
  yarn.lock
Labels: ready for review
