Repository m3ntorship/m3ntorship-ui, pull requests merged in 2022-07, with the labels that each got.

#36 fix: disable interface-name-prefix rule
  .eslintrc.js
Labels: bug, ready for review

#46 Button unit test and fix issues
  src/components/Button/Button.stories.tsx
  src/components/Button/Button.test.tsx
  src/components/Button/__snapshots__/Button.test.tsx.snap
  src/components/Button/index.tsx
  src/components/Button/types.ts
Labels: ready for review

#47 fix: make a release when deploying changes to main branch
  .github/workflows/release.yml
Labels: ready for review

#51 add mdx docs
  .storybook/main.js
  package.json
  src/components/Button/Button.stories.mdx
  src/components/Button/Button.stories.tsx
  yarn.lock
Labels: in progress

#52 Add mdx docs
  src/assets/icons/menu.svg
  src/components/Button/Button.stories.mdx
  src/components/IconButton/IconButton.stories.mdx
  src/components/IconButton/IconButton.stories.tsx
  src/components/Link/Link.stories.mdx
  src/components/Link/Link.stories.tsx
  src/components/Typography/Typography.stories.mdx
  src/components/Typography/Typography.stories.tsx
Labels: ready for review
